Repository badasswp/search-and-replace, pull requests merged in 2024-12, with the labels that each got.

#31 Fix style issues in WP 6.6.2
  CHANGELOG.md
  src/styles/app.scss
Labels: bug

#28 Fix backward compatibility issues due to WP upgrade
  CHANGELOG.md
  search-replace-for-block-editor.php
  src/styles/app.scss
  src/typings/global.d.ts
  src/utils.tsx
Labels: bug

#34 Fix as follow up PR on backward compatibility
  src/index.tsx
  src/shortcut.tsx
  src/styles/app.scss
Labels: bug, duplicate

#29 Release 1.2.2
  CHANGELOG.md
  package.json
  readme.txt
  search-replace-for-block-editor.php
  src/core/app.tsx
  src/core/shortcut.tsx
  src/core/utils.tsx
  src/index.tsx
  src/styles/app.scss
  src/typings/global.d.ts
  tests/filters.test.tsx
  tests/utils.test.tsx
Labels: bug, documentation, good first issue

#19 Introducing search count feature
  CHANGELOG.md
  src/core/app.tsx
Labels: enhancement
