Repository badasswp/search-and-replace, pull requests merged in 2024-11, with the labels that each got.

#10 Fix Inside modal container selection issue
  CHANGELOG.md
  src/app.tsx
Labels: bug

#14 Fix Missing Tooltip component on Search & Replace Icon hover
  CHANGELOG.md
  src/app.tsx
Labels: enhancement

#20 Update doc blocks & code house keeping
  src/app.tsx
  src/utils.tsx
Labels: documentation

#22 Fix block editor selection issue due to iframe
  CHANGELOG.md
  src/app.tsx
  src/utils.tsx
Labels: bug

#24 Chore: Prepare release-1.2.1 branch
  CHANGELOG.md
  README.md
  package.json
  readme.txt
  search-replace-for-block-editor.php
Labels: documentation

#12 Release 1.2.1
  CHANGELOG.md
  README.md
  package.json
  readme.txt
  search-replace-for-block-editor.php
  src/app.tsx
  src/utils.tsx
Labels: bug

#26 Fix timeout issues causing Icon not to load
  CHANGELOG.md
  src/utils.tsx
Labels: bug, good first issue
