Repository badasswp/search-and-replace, pull requests merged in 2025-03, with the labels that each got.

#44 Chore: Enforce WP linting for JS files
  .deployignore
  .editorconfig
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  CHANGELOG.md
  jest.config.js
  package.json
  search-replace-for-block-editor.php
  src/core/app.tsx
  src/core/shortcut.tsx
  src/core/utils.tsx
  src/index.tsx
  tests/filters.test.tsx
  tests/utils.test.tsx
  webpack.config.js
Labels: enhancement

#47 Feat: Add Search icon to Toolbar
  CHANGELOG.md
  assets/screenshot-4.png
  assets/screenshot-5.png
  package.json
  readme.txt
  src/core/shortcut.tsx
  src/core/toolbar.tsx
  src/core/utils.tsx
  src/index.tsx
Labels: enhancement

#49 Chore: Update unit test cases
  CHANGELOG.md
  package.json
  readme.txt
  src/core/utils.tsx
  tests/utils.test.tsx
Labels: enhancement, test

#51 Refactor: use replaceBlockAttribute hook for search and replace logic
  CHANGELOG.md
  readme.txt
  src/core/app.tsx
  src/core/filters.tsx
  src/index.tsx
Labels: enhancement

#42 Feat: Add replaceBlockAttribute hook for searching & replacing custom fields in custom blocks
  README.md
Labels: enhancement

#45 Release 1.4.0
  .deployignore
  .editorconfig
  .eslintignore
  .eslintrc.js
  .github/workflows/ci.yml
  CHANGELOG.md
  README.md
  assets/screenshot-4.png
  assets/screenshot-5.png
  jest.config.js
  package.json
  readme.txt
  search-replace-for-block-editor.php
  src/core/app.tsx
  src/core/filters.tsx
  src/core/shortcut.tsx
  src/core/toolbar.tsx
  src/core/utils.tsx
  src/index.tsx
  tests/filters.test.tsx
  tests/utils.test.tsx
  webpack.config.js
Labels: bug, enhancement, test
